add_executable(exchange_disruptor_tests
  unit/matching_engine.tests.cpp
)
target_link_libraries(exchange_disruptor_tests PRIVATE exchange_disruptor_lib exchange_disruptor_options)
target_set_warnings(exchange_disruptor_tests)

add_test(NAME exchange_disruptor.tests COMMAND $<TARGET_FILE:exchange_disruptor_tests>)

add_executable(exchange_disruptor_tcp_v1_tests
  unit/tcp_v1.tests.cpp
)
target_link_libraries(exchange_disruptor_tcp_v1_tests PRIVATE exchange_disruptor_lib exchange_disruptor_options)
target_set_warnings(exchange_disruptor_tcp_v1_tests)

add_test(NAME exchange_disruptor.tcp_v1.tests COMMAND $<TARGET_FILE:exchange_disruptor_tcp_v1_tests>)
